### ISSUE TITLE
Factor out resource "vga"

### ISSUE THREAD

**Issue by whitequark** [amaranth-lang/amaranth-boards#127]
This resource is intended for R2R DACs attached directly to the FPGA, which is pretty much how it always works in practice.

Boards that use it:
- [ ] DE0
- [ ] DE0-CV
- [ ] DE10-Lite
- [ ] Genesys2
- [ ] Mercury
- [ ] MiSTer
- [ ] Nexys4DDR

**Comment by sporniket** [comment]
There is a PR that has been merged, should this issue be closed ?

**Comment by whitequark** [comment]
Fixed in #160.
