### ISSUE TITLE
Add support for Nandland Go Board

### ISSUE THREAD

**Issue by nono2357** [amaranth-lang/amaranth-boards#145]
Here are the board details:
https://www.nandland.com/goboard/introduction.html

Excellent board for beginners and open source projects.

Thank you.

**Comment by whitequark** [comment]
We do not, in general, accept requests for new board definitions through issues in this repository. I suggest implementing support for this board yourself or finding someone to implement it, and submitting it as a pull request.

**Comment by StephanvanSchaik** [comment]
I ordered the Nandland Go board, and I will gladly write up and test the board definition for it once it arrives. Given that shipping might take about 4-5 business days, I am estimating that to be for the next weekend.

**Comment by kivikakk** [comment]
Just a heads up, this issue can be closed since the merge of #164.
