### ISSUE TITLE
Support to LiteX Acorn baseboard (mini variant)

### ISSUE THREAD

**Issue by ohault** [amaranth-lang/amaranth-boards#247]
https://github.com/enjoy-digital/litex-acorn-baseboard

**Comment by whitequark** [comment]
We don't currently accept feature requests as there is not enough staffing to even review PRs at a good pace.

**Comment by ohault** [comment]
> We don't currently accept feature requests as there is not enough staffing to even review PRs at a good pace.

Can you please keep this ticket open as the PR is not yet done ?

**Comment by whitequark** [comment]
If you have a work-in-progress PR please do post it as a draft.
